# ─────────────────────────────────────────────
#  АВТОЗАПУСК
# ─────────────────────────────────────────────

# Обои
exec-once = awww-daemon

# Панель
exec-once = waybar

# Уведомления
exec-once = swaync

# Индикаторы громкости/яркости (OSD)
exec-once = swayosd-server

# Буфер обмена — копит историю
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Монтирование дисков
exec-once = udiskie --tray

# Polkit (нужен для прав)
exec-once = hyprolkitagent
# Сеть — апплет в трее если нужен (можно убрать, nmtui в терминале)
# exec-once = nm-applet --indicator

# Устанавливаем обои из последней темы
exec-once = ~/.local/bin/theme-apply || swww img ~/Pictures/Wallpapers/default.jpg

# Idle демон (блокировка/сон)
exec-once = hypridle
