font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

background_opacity 0.90
confirm_os_window_close 0
enable_audio_bell no
cursor_shape block
shell_integration enabled

window_padding_width 10
placement_strategy center

foreground #e6e6e6
background #101010
selection_foreground #101010
selection_background #e6e6e6

color0  #2a2a2a
color1  #d78787
color2  #a1b56c
color3  #f0c674
color4  #8fa1b3
color5  #b294bb
color6  #8abeb7
color7  #c5c8c6
color8  #666666
color9  #d78787
color10 #a1b56c
color11 #f0c674
color12 #8fa1b3
color13 #b294bb
color14 #8abeb7
color15 #e6e6e6
